"""AlphaX Builder — Notion 模板生成器

生成可导入 Notion 的模板（Markdown + JSON schema）。
Notion 模板是 2026 年增长最快的数字产品品类之一（$5-$35）。
"""

from __future__ import annotations

import json
import zipfile
from pathlib import Path

from core.genome import Genome, Category
from config import config


TEMPLATES = {
    Category.PRODUCTIVITY: {
        "name": "Productivity OS",
        "pages": [
            {"title": "Dashboard", "icon": "🎯", "blocks": [
                "## This Week's Goals\n- [ ] Priority 1\n- [ ] Priority 2\n- [ ] Priority 3",
                "## Quick Capture\n> Drop ideas here, organize later",
                "## Today's Focus\n1. Most important task\n2. Secondary task\n3. Bonus",
            ]},
            {"title": "Projects", "icon": "📁", "blocks": [
                "## Active Projects\n| Project | Status | Deadline | Next Step |\n|---------|--------|----------|----------|\n| | | | |",
                "## Project Template\n### Overview\n### Milestones\n### Resources",
            ]},
            {"title": "Weekly Review", "icon": "🔄", "blocks": [
                "## Wins This Week\n- \n\n## Challenges\n- \n\n## Next Week Focus\n- ",
                "## Metrics\n- Tasks completed: \n- Deep work hours: \n- Learning hours: ",
            ]},
            {"title": "Knowledge Base", "icon": "🧠", "blocks": [
                "## Categories\n- Technical\n- Business\n- Personal",
                "## Note Template\n### Key Takeaways\n### Action Items\n### Related",
            ]},
        ],
    },
    Category.DATA: {
        "name": "Data Tracker Pro",
        "pages": [
            {"title": "Dashboard", "icon": "📊", "blocks": [
                "## Key Metrics\n| Metric | Current | Target | Trend |\n|--------|---------|--------|-------|\n| | | | |",
                "## Charts View\n> Embed charts here",
            ]},
            {"title": "Data Sources", "icon": "🔗", "blocks": [
                "## Connected Sources\n- [ ] API Connection\n- [ ] CSV Import\n- [ ] Manual Entry",
                "## Data Dictionary\n| Field | Type | Description |\n|-------|------|-------------|\n| | | |",
            ]},
        ],
    },
    Category.AUTOMATION: {
        "name": "Automation Workflow Hub",
        "pages": [
            {"title": "Workflows", "icon": "⚡", "blocks": [
                "## Active Automations\n| Name | Trigger | Action | Status |\n|------|---------|--------|--------|\n| | | | |",
                "## Templates\n### Email Automation\n### Social Media\n### Data Sync",
            ]},
        ],
    },
    Category.CONTENT: {
        "name": "Content Creator Studio",
        "pages": [
            {"title": "Content Calendar", "icon": "📅", "blocks": [
                "## This Month\n| Date | Platform | Content | Status |\n|------|----------|---------|--------|\n| | | | |",
                "## Content Pillars\n1. Educational\n2. Behind-the-scenes\n3. Promotional",
            ]},
            {"title": "Idea Bank", "icon": "💡", "blocks": [
                "## Brain Dump\n- \n\n## Validated Ideas\n- ",
            ]},
            {"title": "Analytics", "icon": "📈", "blocks": [
                "## Weekly Stats\n| Platform | Followers | Engagement | Posts |\n|----------|-----------|------------|-------|\n| | | | |",
            ]},
        ],
    },
}

# Fallback for categories without specific templates
_DEFAULT_TEMPLATE = {
    "name": "Digital Workspace",
    "pages": [
        {"title": "Getting Started", "icon": "🚀", "blocks": [
            "## Welcome\nThis template helps you stay organized and productive.",
            "## Quick Start\n1. Review each page\n2. Customize to your needs\n3. Start using daily",
        ]},
        {"title": "Dashboard", "icon": "📋", "blocks": [
            "## Daily Overview\n- [ ] Morning review\n- [ ] Priority tasks\n- [ ] End of day reflection",
        ]},
    ],
}


class NotionBuilder:
    """生成 Notion 模板"""

    _build_dir: Path = config.data_dir / "builds"

    def build(self, genome: Genome, organism_id: str) -> Path:
        self._build_dir.mkdir(parents=True, exist_ok=True)
        work_dir = self._build_dir / f"notion_{organism_id}"
        work_dir.mkdir(exist_ok=True)

        tmpl = TEMPLATES.get(genome.category, _DEFAULT_TEMPLATE)

        # Generate importable markdown files
        pages_md = []
        for i, page in enumerate(tmpl["pages"]):
            md = f"# {page['icon']} {page['title']}\n\n"
            md += "\n\n---\n\n".join(page["blocks"])
            md += "\n\n---\n*Generated by Alpha X*\n"
            fpath = work_dir / f"{i:02d}_{page['title'].lower().replace(' ', '_')}.md"
            fpath.write_text(md)
            pages_md.append(fpath.name)

        # Generate metadata
        meta = {
            "template_name": tmpl["name"],
            "category": genome.category.value,
            "description": f"{genome.benefit}. Ready-to-use Notion template system.",
            "pages": len(tmpl["pages"]),
            "instructions": [
                "1. Open Notion and create a new workspace",
                "2. Import each .md file into a new page",
                "3. Arrange pages in sidebar as desired",
                "4. Customize content to your needs",
            ],
            "target_audience": genome.target_market.value,
            "tags": [genome.category.value, "notion", "template", "productivity"],
        }
        (work_dir / "template.json").write_text(json.dumps(meta, indent=2, ensure_ascii=False))
        (work_dir / "README.md").write_text(self._readme(genome, meta))

        zip_path = self._build_dir / f"{organism_id}_notion.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for f in work_dir.iterdir():
                zf.write(f, f.name)

        return zip_path

    def _readme(self, genome: Genome, meta: dict) -> str:
        page_names = [p["title"] for p in TEMPLATES.get(
            genome.category, _DEFAULT_TEMPLATE)["pages"]]
        return f"""# {meta['template_name']}

{meta['description']}

## What's Included
{chr(10).join(f'- {p}' for p in page_names)} ({meta['pages']} pages)

## How to Import
{chr(10).join(meta['instructions'])}

## Who Is This For
{genome.target_market.value.replace('_', ' ').title()} users

---
Built by Alpha X | {genome.express()}
"""
